package com.plus3.privilege.dao.mapper;

import com.plus3.privilege.dao.entity.Permission;

import java.util.List;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int updateByPrimaryKey(Permission record);

    List<Permission> selectAll();
}