package com.plus3.privilege.dao.mapper;

import com.plus3.privilege.dao.entity.RoleOfGroup;

public interface RoleOfGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_of_group
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_of_group
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int insert(RoleOfGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_of_group
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int insertSelective(RoleOfGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_of_group
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    RoleOfGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_of_group
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int updateByPrimaryKeySelective(RoleOfGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_of_group
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    int updateByPrimaryKey(RoleOfGroup record);
}