package com.plus3.privilege.dao.entity;

import java.io.Serializable;

public class Admin implements Serializable {
    private Integer id;
    private String name;
    private String password;
    private String passwordSalt;
    private String nickName;
    private Integer groupId;
    private String groupToken;
    private String description;
    private Integer creatorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.name
     *
     * @return the value of admin.name
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.name
     *
     * @param name the value for admin.name
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password_salt
     *
     * @return the value of admin.password_salt
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password_salt
     *
     * @param passwordSalt the value for admin.password_salt
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.nick_name
     *
     * @return the value of admin.nick_name
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.nick_name
     *
     * @param nickName the value for admin.nick_name
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.group_id
     *
     * @return the value of admin.group_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.group_id
     *
     * @param groupId the value for admin.group_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.group_token
     *
     * @return the value of admin.group_token
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getGroupToken() {
        return groupToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.group_token
     *
     * @param groupToken the value for admin.group_token
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setGroupToken(String groupToken) {
        this.groupToken = groupToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.description
     *
     * @return the value of admin.description
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.description
     *
     * @param description the value for admin.description
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getCreatorId() {
        return creatorId;
    }
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }
}