package com.plus3.privilege.dao.entity;

import java.io.Serializable;

public class Group implements Serializable {
    private Integer id;
    private String name;
    private String description;
    private String token;
    private Integer parentId;
    private String domain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.id
     *
     * @return the value of group.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.id
     *
     * @param id the value for group.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.name
     *
     * @return the value of group.name
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.name
     *
     * @param name the value for group.name
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.description
     *
     * @return the value of group.description
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.description
     *
     * @param description the value for group.description
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.token
     *
     * @return the value of group.token
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.token
     *
     * @param token the value for group.token
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.parent_id
     *
     * @return the value of group.parent_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.parent_id
     *
     * @param parentId the value for group.parent_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.domain
     *
     * @return the value of group.domain
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.domain
     *
     * @param domain the value for group.domain
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }
}