package com.plus3.privilege.dao.entity;

import java.io.Serializable;

public class PermissionOfRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_of_role.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_of_role.role_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_of_role.permission_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    private Integer permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_of_role.extra
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    private String extra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_of_role.id
     *
     * @return the value of permission_of_role.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_of_role.id
     *
     * @param id the value for permission_of_role.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_of_role.role_id
     *
     * @return the value of permission_of_role.role_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_of_role.role_id
     *
     * @param roleId the value for permission_of_role.role_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_of_role.permission_id
     *
     * @return the value of permission_of_role.permission_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_of_role.permission_id
     *
     * @param permissionId the value for permission_of_role.permission_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_of_role.extra
     *
     * @return the value of permission_of_role.extra
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_of_role.extra
     *
     * @param extra the value for permission_of_role.extra
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setExtra(String extra) {
        this.extra = extra;
    }

    //===================================================================================
    @Override
    public boolean equals(Object obj) {
        if (obj instanceof PermissionOfRole == false)
            return false;
        if (obj == this)
            return true;

        PermissionOfRole permissionOfRole = (PermissionOfRole) obj;
        if (permissionOfRole.getRoleId() == roleId
                && permissionOfRole.getPermissionId() == permissionId)
            return true;

        return false;
    }
}