package com.plus3.privilege.dao.entity;

import java.io.Serializable;

public class Role implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.group_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.group_token
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    private String groupToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.description
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.group_id
     *
     * @return the value of role.group_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.group_id
     *
     * @param groupId the value for role.group_id
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.group_token
     *
     * @return the value of role.group_token
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getGroupToken() {
        return groupToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.group_token
     *
     * @param groupToken the value for role.group_token
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setGroupToken(String groupToken) {
        this.groupToken = groupToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.description
     *
     * @return the value of role.description
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.description
     *
     * @param description the value for role.description
     *
     * @mbggenerated Mon Dec 18 14:27:29 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}